#!/usr/bin/env python3
import os, os.path
import json
import base64
import sys
import argparse
from urllib.request import urlopen

IGNORES_DIR = os.path.join(os.path.dirname(__file__), "gitignore")
CACHE_PATH = os.path.expanduser("~/.ignore-via-github")

HEAD_URL = "https://api.github.com/repos/github/gitignore/git/refs/heads/master"
TREE_URL = "https://api.github.com/repos/github/gitignore/git/trees/%s"

def json_get(url):
    return json.loads(urlopen(url).read().decode('utf8'))

def path_match(stack, ignorefile):
    return stack.lower() == ignorefile.lower().split('.gitignore')[0]

# Cache it
def cache_content(content, stack):
    if not os.path.exists(CACHE_PATH):
        print("Creating gitignore cache in %s" % CACHE_PATH)
        os.mkdir(CACHE_PATH)
    with open(os.path.join(CACHE_PATH, stack.lower()), 'w') as f:
        print("Caching file at %s" % os.path.join(CACHE_PATH, stack.lower()))
        f.write(content)


# Local Ops

def try_cached(stack):
    cachepath = file_find(stack, CACHE_PATH)
    if cachepath:
        with open(cachepath, 'r') as ignorefile:
            return ignorefile.read()

def file_find(stack, root):
    if os.path.exists(root):
        for dirpath, dirs, files in os.walk(root):
            for fn in files:
                if path_match(stack, fn):
                    return os.path.join(dirpath, fn)

# Querying Github Ops

def get_head_sha():
    data = json_get(HEAD_URL)
    return data["object"]["sha"]

def tree_find(sha, stack):
    data = json_get(TREE_URL % sha)
    subdirs = []
    for obj in data['tree']:
        print("Github Obj: %s" % str(obj['path']))
        if obj['type'] == 'tree':
            subdirs.append(obj)
        elif obj['type'] == 'blob':
            if path_match(stack, obj['path']):
                return obj['url']
        else:
            pass
    for subdir in subdirs:
        url = tree_find(subdir['sha'], stack)
        if url:
            return url

def try_github(stack):
    head_sha = get_head_sha()
    url = tree_find(head_sha, stack)
    if url:
        data = json_get(url)
        encoded = data['content']
        if data['encoding'] == 'base64':
            content = base64.b64decode(encoded)
            return content.decode('utf8')
        else:
            print("Cannot decode Github blob w/ encoding %s" % data['encoding'])



def exec_ignore(ignore_txt, t):
    with open('.gitignore', 'a') as gitignore:
        gitignore.write('\n' + ignore_txt + '\n')
    os.system('git add .gitignore')
    os.system('git commit .gitignore -m "Ignoring files for %s, (see https://github.com/github/gitignore.git)"' % t)

def ignore(stack):
    ignorefile = try_cached(stack)
    if not ignorefile:
        ignorefile = try_github(stack)
        if not ignorefile:
            print("No .gitignore file found for %s anywhere" % stack)
            sys.exit(1)
        else:
            cache_content(ignorefile, stack)
    exec_ignore(ignorefile, stack)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('stack', help='stack whose ugly files you wish to ignore')
    args = parser.parse_args()
    ignore(args.stack)
